### ISSUE TITLE
set color

### ISSUE THREAD

**Issue by AndreyKindin** [mabunixda/node-red-contrib-alexa-home#19]
Hi,
if i try to set a color  i get this

`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at AlexaHomeController.controlItem (/home/pi/.node-red/node_modules/node-red-contrib-alexa-home/alexa/alexa-home-controller.js:367:27)
    at /home/pi/.node-red/node_modules/node-red-contrib-alexa-home/alexa/alexa-home-controller.js:114:14
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at param (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at query (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
`

the reason for this is that unparseable thing
`{ '{ "on": true, "xy": ': { '0.7006062331309042,0.2993009868421053': '' } }`
this is a console log from AlexaHomeController.prototype.controlItem -> request.body

**Comment by mabunixda** [comment]
Yeah i reuse the http server of node-red. there is already a json parser working and so the body is a json representation of the content. I did not get a solution to get the "inner"-body of the request body.

**Comment by AndreyKindin** [comment]
this is output from  request.body.  if i try to get payloadRaw i get something like this { "on": true, "xy":  and this can't be parst

**Comment by mabunixda** [comment]
I did not find any solution getting the raw body before it was json parsed in the request object. 
I also tried to inject a middleware to copy the body before it gets parsed without success :(

**Comment by AndreyKindin** [comment]
not nice, but it works
replace 
`var payloadRaw = Object.keys(request.body)[0];`
with

`var body = JSON.stringify(request.body);
		var payloadRaw;
		if(body.indexOf('xy') > 0){
			payloadRaw = body.replace("{\"{","{").replace(" \":{\"","[").replace("\":\"\"}","]").replace(/\\/g,"");
		}else{
			payloadRaw = Object.keys(request.body)[0];
		}
`

**Comment by mabunixda** [comment]
yeah i tried in the meantime the same approach - quite unsatisified with this solution but it works as hack till i find a solution with express and getting the rawBody...

Can you try the current dev branch? I added all the logic/data to make it valid.

**Comment by AndreyKindin** [comment]
somthing is wrong i get [debug] No Alexa Home Controller available

**Comment by AndreyKindin** [comment]
in set-state.json you have 
 {"success":{"/lights/1/state/sat": [{{ x }}, {{ y }} ] }},
instead of
 {"success":{"/lights/1/state/xy": [{{ x }}, {{ y }} ] }},

and 

the error comes from
var app = RED.httpAdmin;
    app.use(bodyParser.json({
        verify: function (req, res, buf, encoding) {
            console.log("test")
            // sha1 content
            var hash = crypto.createHash('sha1');
            hash.update(buf);
            req.hasha = hash.digest('hex');
            console.log("hash", req.hasha);

            // get rawBody        
            req.rawBody = buf.toString();
            console.log("rawBody", req.rawBody);

        }
    }));

**Comment by mabunixda** [comment]
on the last 2 commits both errors should be gone. 2nd is from getting a better workaround of your "hack" ;-)

**Comment by AndreyKindin** [comment]
👍

**Comment by mabunixda** [comment]
is now online with 1.0.4
